<?php


namespace Omnipay\Payeer\Message;


class PurchaseRequest extends AbstractRequest
{

    /**
     * Get the raw data array for this message. The format of this varies from gateway to
     * gateway, but will usually be either an associative array, or a SimpleXMLElement.
     *
     * @return mixed
     */
    public function getData()
    {
        // TODO: Implement getData() method.
    }

    public function sendData($data)
    {
        return parent::sendData($data); // TODO: Change the autogenerated stub
    }
}
